CREATE TABLE IF NOT EXISTS `log` (
    `ID` VARBINARY(16) NOT NULL PRIMARY KEY,
    `DATE` TIMESTAMP NOT NULL,
    `IP` INTEGER NOT NULL,    
    `METHOD` VARCHAR(255) NOT NULL,
    `RESPONSE` INTEGER NOT NULL,
    `AGENT` VARCHAR(255) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;